name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Install xvfb
      run: sudo apt-get install -y xvfb
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    
    - name: Run tests with xvfb
      run: xvfb-run --auto-servernum mvn test
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: FileVault-shaded
        path: target/FileVault-shaded-*.jar 