name: Code Quality with SonarCloud

on:
  # Aktiviere den Workflow nur auf Pull Requests, nicht bei Pushes
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones sollten vermieden werden für bessere Relevanz der SonarCloud-Analyse
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Install xvfb
        run: sudo apt-get install -y xvfb
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build with Maven
        run: xvfb-run --auto-servernum mvn -B verify
      
      # Führe SonarCloud nur für Pull Requests aus.
      - name: SonarCloud Scan
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        # Die sonar-project.properties Datei im Wurzelverzeichnis wird automatisch verwendet 