name: Build and Publish Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      
      - name: Install xvfb
        run: sudo apt-get install -y xvfb
      
      - name: Build with Maven
        run: xvfb-run --auto-servernum mvn -B package --file pom.xml
      
      - name: Extract version from pom.xml
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      
      - name: Update version if needed
        run: |
          # If this is a GitHub release with a tag v1.2.3, extract the version number
          if [[ "${{ github.ref }}" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            RELEASE_VERSION="${BASH_REMATCH[1]}"
            echo "Updating version in pom.xml from ${{ steps.get_version.outputs.VERSION }} to ${RELEASE_VERSION}"
            mvn versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false
          fi
      
      - name: Copy settings.xml
        run: mkdir -p ~/.m2 && cp .github/workflows/settings.xml ~/.m2/settings.xml
      
      - name: Publish package to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileVault-shaded-${{ steps.get_version.outputs.VERSION }}
          path: target/FileVault-shaded.jar
      
      - name: Add package to release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/FileVault-shaded.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 